# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('ef7e3c91cf8370efdba8ce11a4f272cc_MTk3NTIyMjAxMy0wMy0xMSAwOTozNDo1Ni4xMDQzNjc')
  end)
end
